apiVersion: v1
kind: Pod
metadata:
  name: dubbo-demo-provider
  namespace: higress-system
spec:
  containers:
  - name: dubbo-demo-provider
    image: registry.cn-hangzhou.aliyuncs.com/hinsteny/dubbo-provider-demo:0.0.1
    ports:
    - containerPort: 20880